config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users, except:[:create, :show, :destroy, :edit, :update] do
    resources :tweets
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  get "/:username", to: "users#show", as: "username"
  
  get '/users/:username/followview', to: 'users#followview', as: "users_followview" # or match for older Rails versions

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  # returns an array of follows a user gave to someone else
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
  # returns an array of other users who the user has followed
  has_many :followings, through: :given_follows, source: :followed_user

  # Will return an array of follows for the given user instance
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"
  # Will return an array of users who follow the user instance
  has_many :followers, through: :received_follows, source: :follower

  validates :name, presence: true, length: { minimum: 6, maximun: 50 }
  validates :username, presence: true, length: { minimum: 6, maximun: 20 }
  validates :username, uniqueness: true
  validates :username, :format => { :with => /\A(?=.*[a-z])[a-z\d]+\Z/i }
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end
 
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
      flash[:notice] = "User was successfully created"      
    else
      render 'new'     
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:notice] = "User was successfully updated." 
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
    flash[:notice] = "User was successfully destroyed." 
  end

end

private

    def set_user
      @user = User.find(params[:id])
    end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  
  def new
    super
  end

  
  def create
    super
  end

  
  def edit
    super
  end

  
  def update
    super
  end

  
  def destroy
    super
  end

  
  def cancel
    super
  end

  protected

  
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name, :username])
  end

  
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :name, :username])
  end

  
  def after_sign_up_path_for(resource)
    super(resource)
  end

  
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy followview ]

  def index
    @users = User.all
    if user_signed_in?
      current_followings = current_user.followings
      @tweets = current_user.tweets
      current_followings.each do |following_user|
        @tweets = @tweets.or(following_user.tweets)
      end
      @tweets = @tweets.order([created_at: :desc]).paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @tweets = @user.tweets
    @tweets = @tweets.order([created_at: :desc]).paginate(page: params[:page], per_page: 10)
  end

  def edit
  end
 
  def new
    @user = User.new
  end

  def followview
    # @user_followers = @user.followers
    # @user_followers = @user_followers.order([name: :asc])

  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
      flash[:notice] = "User was successfully created"      
    else
      render 'new'     
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:notice] = "User was successfully updated." 
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
    flash[:notice] = "User was successfully destroyed." 
  end

  def follow
    @user = User.find(params[:id])
    current_user.followings << @user
    redirect_back(fallback_location: users_path)
  end
  
  def unfollow
    @user = User.find(params[:id])
    current_user.given_follows.find_by(followed_user_id: @user.id).destroy
    redirect_back(fallback_location: users_path)
  end

end

private

    def set_user
      @user = User.find_by(username: params[:username])
    end

    def user_params
      params.require(:user).permit(:name, :username)
    end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/followview.html.erb
<div class="card show-card">
  <div class="card-header">
    <div class="d-flex flex-row">
      <%= link_to username_path(@user.username) do %>
        <span class="fas fa-arrow-left arrow-left-icon" aria-hidden="true"></span>
      <% end %>
      
      <h2 class="username-profile-label" ><%=@user.name%></h2>
    
      
    </div>
    <p class="card-text username-follow-view"> <%=link_to "@#{@user.username}", username_path(@user.username) %></p>
  </div>
  <div class="card-body">

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Followers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Following</a>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <ul class="list-group list-group-flush">
          
          <% User.order([name: :asc]).each do |user| %>
            <%if @user.followers.include?(user) %>
              <li class="list-group-item">
                <div class="d-flex flex-row">
                  
                  <div>
                    <h5 class="card-title"><%=user.name%></h5>
                    <div class="d-flex flex-row name-username-followview">
                      <%=link_to "@#{user.username}", username_path(user.username) %>
                      <% if current_user.followers.include?(user) %>
                        <span class="badge badge-secondary badge-follow">Follows you</span>
                      <%end%>
                    </div>
                  </div>

                  <%if user.id!=current_user.id%>
                    <%if current_user.followings.include?(user) %>
                      <%= button_to 'Unfollow', unfollow_user_path(user), method: "POST", class:"btn btn-outline-primary btn-sm follow-button-view"%>
                      <%else%>
                        <%= button_to 'Follow', follow_user_path(user), method: "POST", class:"btn btn-outline-primary btn-sm follow-button-view"%>
                    <%end%>
                  <%end%>
                  
                </div>
              </li>
              
            <%end%>
          <%end%>
        </ul>
      </div>

      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        
        <ul class="list-group list-group-flush">
          
          <% User.order([name: :asc]).each do |user| %>
            <%if @user.followings.include?(user) %>
              <li class="list-group-item">
                <div class="d-flex flex-row">
            
                  <div>
                    <h5 class="card-title"><%=user.name%></h5>
                    <div class="d-flex flex-row name-username-followview">
                      <%=link_to "@#{user.username}", username_path(user.username) %>
                      <%if current_user.followers.include?(user) %>
                        <span class="badge badge-secondary badge-follow">Follows you</span>
                      <%end%>
                    </div>
                  </div>

                  <%if user.id!=current_user.id%>
                    <%if current_user.followings.include?(user) %>
                      <%= button_to 'Unfollow', unfollow_user_path(user), method: "POST", class:"btn btn-outline-primary btn-sm follow-button-view"%>
                      <%else%>
                        <%= button_to 'Follow', follow_user_path(user), method: "POST", class:"btn btn-outline-primary btn-sm follow-button-view"%>
                    <%end%>
                  <%end%>

                </div>
              </li>
            <%end%>
          <%end%> 
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="d-flex flex-row">
  <% if user_signed_in? %>
    <div class="card card-home">
      <div class="card-header">
        Home
      </div>

      <div class="card-body">
        <% if user_signed_in? %>
          <h5><%=current_user.name %></h5>
          <%= button_to 'Go tweet', new_user_tweet_path(current_user), method: :get, class:"btn btn-primary"%>

            <ul class="list-group list-group-flush group-flush group-tweets">

              <% @tweets.each do |tweet| %>

                    
                <li class="list-group-item">
                  <div class="d-flex flex-row">
                    <span class="fas fa-user-circle mini-profile-icon" aria-hidden="true"></span>
                    <p class="card-text name-label-tweet"><%=tweet.user.name%></p>
                    <p class="card-text username-label-tweet"> <%=link_to "@#{tweet.user.username}", username_path(tweet.user.username) %></p>
                    <p class="time-ago-label"><%= time_ago_in_words(tweet.created_at) %> ago</p>
                  </div>
                  <p class="tweet-style"><%=tweet.post%></p>
                </li>
                    
                           
              <% end %>
            </ul>

        <%end%>
      </div>
    </div>
  <%end%>

  <% if user_signed_in? %>
    <div class="card follow-card">

      <div class="card-header">
        Who to follow
      </div>

      <ul class="list-group list-group-flush">
        <% @users.each do |user| %>
          <%if user!=current_user%>
            
            <li class="list-group-item list-group-follow">
              <div class="d-flex flex-row">

                <div>
                  <h5 class="card-title"><%=user.name%></h5>
                  <div class="d-flex flex-row name-username-followview">
                    <%=link_to "@#{user.username}", username_path(user.username) %>
                    <% if current_user.followers.include?(user) %>
                      <span class="badge badge-secondary badge-follow">Follows you</span>
                    <%end%>
                  </div>
                </div>

                <%if current_user.followings.include?(user) %>
                  <%= button_to 'Unfollow', unfollow_user_path(user), method: "POST", class:"btn btn-outline-primary btn-sm follow-button-index"%>
                  <%else%>
                    <%= button_to 'Follow', follow_user_path(user), method: "POST", class:"btn btn-outline-primary btn-sm follow-button-index"%>
                <%end%>

              </div>
            </li>
            
          <% end %>

        <% end %>
      </ul>
    </div>
  <% end %>
</div>
<% if user_signed_in? %>
  <%= will_paginate @tweets %>
<% end %>

app/views/users/show.html.erb
<div class="card show-card">
  <div class="card-header">
    <div class="d-flex flex-row">
      <%= link_to users_path do %>
        <span class="fas fa-arrow-left arrow-left-icon" aria-hidden="true"></span>
      <% end %>
      
      <h2 class="username-profile-label" ><%=@user.name%></h2>      
    </div>
  </div>
  <div class="card-body">
    <span class="fas fa-user-circle profile-picture" aria-hidden="true"></span>
    <div>
      <h5 class="card-title"><%=@user.name%></h5>
      <p class="card-text username-label">@<%=@user.username%></p>
      <p class="time-ago-label">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>
    </div>
    <%if @user==current_user%>
      <%= button_to 'Edit profile', edit_user_registration_path, method: :get, class:"btn btn-outline-primary edit-user-button"%>  
      <%else%>
        <%if current_user.followings.include?(@user)%>
          <%= button_to 'Unfollow', unfollow_user_path(@user), method: "POST", class:"btn btn-outline-primary edit-user-button"%>
          <%else%>
            <%= button_to 'Follow', follow_user_path(@user), method: "POST", class:"btn btn-outline-primary edit-user-button"%>
        <%end%>

    <%end%>
    
    <div class="d-flex flex-row follow-section">
      <p class="card-text following-label"><%=link_to "#{@user.followings.count} following", users_followview_path(@user.username) %> </p>
      <p class="card-text followers-label"><%=link_to "#{@user.followers.count} followers", users_followview_path(@user.username) %></p>
    </div>

      <ul class="list-group list-group-flush">
        <% @tweets.each do |tweet| %>
          <li class="list-group-item">
            <div class="d-flex flex-row">
              <span class="fas fa-user-circle mini-profile-icon" aria-hidden="true"></span>
              <p class="card-text name-label-tweet"><%=@user.name%></p>
              <p class="card-text username-label-tweet"> <%=link_to "@#{@user.username}", username_path(@user.username) %></p>
              <p class="time-ago-label"><%= time_ago_in_words(tweet.created_at) %> ago</p>
            </div>
            <p class="tweet-style"><%=tweet.post%></p>
          </li>
        <% end %>
      </ul>
      
  </div>
</div>

<%= will_paginate @tweets %>