config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users, except:[:create, :show, :destroy, :edit, :update] do
    resources :tweets
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  get "/:username", to: "users#show", as: "username"
  
  get '/users/:username/followview', to: 'users#followview', as: "users_followview" # or match for older Rails versions

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <nav class="navbar navbar-dark bg-dark">
    
      <a class="navbar-brand navbar-title">Twitter clone</a>
        <% if !user_signed_in? %>
        
          <%= button_to 'Sign up', new_user_registration_path, method: :get, class:"btn btn-primary signup-button"%>
          <%= button_to 'Sign in', new_user_session_path, method: :get, class:"btn btn-light signin-button"%>
          
          <%else%>
            <div class="d-flex flex-row">
              <%= link_to username_path(current_user.username) do %>
                <h2><span class="badge badge-primary navbar-username-label"><%=current_user.name%></span></h2>
              <% end %>
              <%= button_to 'Log out', destroy_user_session_path, method: :delete, class:"btn btn-secondary signin-button"%>
            </div>
            
        <% end %>
    </nav>

    <ul class="nav flex-column nav-flex">

      <span class="fas fa-kiwi-bird navbar-logo" aria-hidden="true"></span>

      <li class="nav-item">
        <%= link_to users_path do %>
          <span class="fas fa-home navbar-home-icon" aria-hidden="true"></span>
        <% end %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to username_path(current_user.username) do %>
            <span class="fas fa-user-alt navbar-icon" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </li>

      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to new_user_tweet_path(current_user) do %>
            <span class="far fa-edit navbar-icon" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </li>
      
    </ul>
    
    <%= yield %>
  </body>
</html>